.TH MAC-CEL 1
.SH NAME
mac-cel \- remove mouse acceleration
.SH DESCRIPTION
.B mac-cel
is a simple program to remove mouse acceleration on Mac OSX.
.SH "EXIT STATUS"
.TP
.B 0
Successful operation.
.TP
.B 1
Failed to acquire handle.
.SH BUGS
Please report any bugs to https://github.com/cdown/mac-cel/issues.
.SH COPYRIGHT
Copyright 2011 Christopher Down <iofc.org@christopher.down>.

This is free software; see the COPYING file for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
